# Generated by Django 3.2.5 on 2021-10-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211003_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
