# Generated by Django 3.2.5 on 2021-10-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_blog_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pro_img',
            field=models.ImageField(blank=True, default='/static/img/profile.png', null=True, upload_to='media/'),
        ),
    ]
