# Generated by Django 3.2.5 on 2021-10-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_followercount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowerCount',
        ),
    ]
