# Generated by Django 3.2.5 on 2021-10-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_answeredblog_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnsweredBlog',
        ),
    ]
