# Generated by Django 3.2.5 on 2021-10-08 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20211008_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='another_user',
            field=models.ManyToManyField(related_name='another_user', to='home.Profile'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
        ),
    ]
