# Generated by Django 3.2.5 on 2021-10-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20211008_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='face_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='inst_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='pint_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
