# Generated by Django 3.2.5 on 2021-10-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20211009_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forget_password_token',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
