# Generated by Django 3.2.5 on 2021-10-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_profile_forget_password_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='face_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='inst_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pint_url',
        ),
    ]
