# Generated by Django 3.2.5 on 2021-10-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_blog_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_img',
            field=models.ImageField(blank=True, default='wallpaperflare.com_wallpaper.jpg', null=True, upload_to='media/'),
        ),
    ]
